### ISSUE TITLE
Error: FormData is not defined

### ISSUE THREAD

**Issue by fredericbarthelet** [gladiaio/gladia-sdk-js#30]
Hi there 👋

I'm encountering an issue while using your SDK with the following code snippet :

```ts
    const gladiaClient = gladia({ apiKey: "****" });
    const result = await gladiaClient.audioTranscription({
        audio: new Blob([readFileSync("myFilePath")]),
        output_format: 'json'
    });
```

## Environment

- OS : MacOS Ventura 13.2.1
- Nodejs version : `v16.20.0`
- SDK version : `v0.10.71`
- Bundler : vite
- Destination environment : AWS Lambda

TS config :

```json
{
  "extends": "@tsconfig/node16/tsconfig.json",
  "compilerOptions": {
    "module": "esnext",
  }
}
```

## Error and stack trace
```
Error: FormData is not defined
   ~/mysite/node_modules/.pnpm/@gladiaio+sdk@0.10.71/node_modules/@gladiaio/sdk/lib/esm/client/from-audio-to-text.js:12
           const formData = new FormData();
                            ^

       at FromAudioToText.audioTranscription (~/mysite/node_modules/.pnpm/@gladiaio+sdk@0.10.71/node_modules/@gladiaio/sdk/lib/esm/client/from-audio-to-text.js:12:26)
       at Builder.audioTranscription (~/mysite/node_modules/.pnpm/@gladiaio+sdk@0.10.71/node_modules/@gladiaio/sdk/lib/esm/client/shortcuts.js:5:42)
       at transcribe (~/mysite/packages/core/src/gladia.ts:15:39)
       at default (~/mysite/packages/functions/src/generateSubtitles.ts:32:31)
       at async file:///****/mysite/node_modules/.pnpm/sst@2.14.0/node_modules/sst/support/nodejs-runtime/index.mjs:146:16
```

My best guess is a problem regarding FormData polyfill. Do you have any idea what I'm missing here ?

Thanks for your help !

**Comment by sboudouk** [comment]
Hey @fredericbarthelet ,

Thanks for posting your issue here.

This SDK will be deprecated anytime soon in profit of a new coming one, in the meantime, if you want to use gladia you will have to use the api directly.

If you need a TypeScript or JavaScript example , let me know and It will be a pleasure to provide one.

**Comment by sboudouk** [comment]
Glad you like it @fredericbarthelet !

I'm closing this and will close this repo until the next version is out, thanks for you support.
